features:
  - efi_stub
  - ipv6
  - initramfs
  #- serial

root_label: "LABEL=rootfs"

templates:
  - base.config
  - fs-basic.config
  - fs-fuse.config
  - host-amd.config
  - host-gentoo.config
  - host-x86_64.config
  - kspp.config
  - storage-crypt.config
  - storage-nvme.config
  - storage-usb.config
  - virt-docker.config
  - virt-general.config
